name: dart_polymer_examples
description: Polymer.dart, Web Components, and Dart
homepage: https://github.com/sethladd/dart-polymer-dart-examples
environment:
  sdk: any

dependencies:
  google_oauth2_client: any
  google_plus_v1_api: any
  js: any
  polymer: any

transformers:
- polymer:
    entry_points:
    - web/auto_complete/index.html
